<a href="https://colab.research.google.com/github/tkys/multi-label_text_classifiier_bideirection-LSTM/blob/master/%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%81%AEmulti_label_LSTM_(bideirection)%E3%81%A7%E3%80%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

In [0]:
multi_flags = [['dog', 'cat'],['car', 'house','book'],['cat', 'phone'], ['dog', 'park'], ['phone'], ['book', 'art', 'commedy'] ]

In [0]:
len(multi_flags)

6

In [0]:
label = mlb.fit_transform(multi_flags)

In [0]:
label

array([[0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 0, 0, 0]])

In [0]:
label.shape

(6, 9)

In [0]:
mlb.classes_

array(['art', 'book', 'car', 'cat', 'commedy', 'dog', 'house', 'park',
       'phone'], dtype=object)

In [0]:
import pandas as pd
import json

In [0]:
df = pd.read_json('./comment.json')

In [0]:
basket_multi_label = basket["labels"]

In [0]:
basket_multi_label.shape

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation

In [0]:
# ダミーデータ作成
import numpy as np
data = np.random.random((7, 100))
labels = np.random.randint(10, size=(1000, 1))

# ラベルデータをカテゴリの1-hotベクトルにエンコードする
one_hot_labels = keras.utils.to_categorical(labels, num_classes=10)


In [0]:
data.shape

(7, 100)

In [0]:
data[0]

array([0.99312661, 0.49650889, 0.24723595, 0.8636536 , 0.02443464,
       0.46245866, 0.40816314, 0.36417159, 0.59047631, 0.48332604,
       0.26600714, 0.77840252, 0.95456599, 0.87952298, 0.10004578,
       0.72333041, 0.74973866, 0.15300874, 0.24853535, 0.61700221,
       0.77766589, 0.20730891, 0.39902591, 0.72877655, 0.66277613,
       0.32886197, 0.74946711, 0.42252744, 0.18988072, 0.63538004,
       0.42457248, 0.03281941, 0.92506082, 0.71919226, 0.17932752,
       0.58666436, 0.49556614, 0.47751079, 0.42921195, 0.41822084,
       0.54902125, 0.86028256, 0.66689817, 0.29872265, 0.71979409,
       0.37201589, 0.1682465 , 0.94988699, 0.18893233, 0.21754908,
       0.84103798, 0.91461265, 0.03417606, 0.11595067, 0.57418804,
       0.28438209, 0.13585103, 0.10228   , 0.25960331, 0.48375102,
       0.15392286, 0.87320285, 0.22223044, 0.61785551, 0.7957786 ,
       0.60294676, 0.8929636 , 0.08783984, 0.65304302, 0.22884022,
       0.63380665, 0.96074956, 0.30661246, 0.59176806, 0.90406

In [0]:
one_hot_labels.shape

(1000, 10)

In [0]:
one_hot_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [0]:
# 1つの入力から10クラスの分類を行なう場合について（カテゴリ分類）

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(16, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


# 各イテレーションのバッチサイズを32で学習を行なう
history = model.fit(data, label, epochs=10, batch_size=32)

Epoch 1/10
7/7 [==============================] - 0s 37ms/step - loss: 5.1113 - acc: 0.0000e+00
Epoch 2/10
7/7 [==============================] - 0s 249us/step - loss: 4.9548 - acc: 0.0000e+00
Epoch 3/10
7/7 [==============================] - 0s 748us/step - loss: 4.8597 - acc: 0.0000e+00
Epoch 4/10
7/7 [==============================] - 0s 265us/step - loss: 4.7823 - acc: 0.0000e+00
Epoch 5/10
7/7 [==============================] - 0s 253us/step - loss: 4.7207 - acc: 0.0000e+00
Epoch 6/10
7/7 [==============================] - 0s 257us/step - loss: 4.6754 - acc: 0.0000e+00
Epoch 7/10
7/7 [==============================] - 0s 228us/step - loss: 4.6396 - acc: 0.0000e+00
Epoch 8/10
7/7 [==============================] - 0s 258us/step - loss: 4.6116 - acc: 0.1429
Epoch 9/10
7/7 [==============================] - 0s 209us/step - loss: 4.5693 - acc: 0.2857
Epoch 10/10
7/7 [==============================] - 0s 253us/step - loss: 4.5366 - acc: 0.4286


In [0]:
model.predict(np.random.random((1, 100)))

array([[0.08878566, 0.13400522, 0.10360324, 0.11037378, 0.13499375,
        0.07659661, 0.06164777, 0.07876155, 0.10884176, 0.10239062]],
      dtype=float32)

In [0]:
model.predict_proba(np.random.random((1, 100)))

array([[0.07577451, 0.14482605, 0.09925856, 0.11745218, 0.15235624,
        0.06853005, 0.06241183, 0.08314951, 0.08447716, 0.11176385]],
      dtype=float32)

In [0]:
model.predict_classes(np.random.random((1, 100)))

array([1])

In [0]:
# 1つの入力から10クラスの分類を行なう場合について（カテゴリ分類）

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(16, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])


# 各イテレーションのバッチサイズを32で学習を行なう
history = model.fit(data, label, epochs=10, batch_size=32)

Epoch 1/10
7/7 [==============================] - 0s 48ms/step - loss: 0.6006 - acc: 0.7857
Epoch 2/10
7/7 [==============================] - 0s 275us/step - loss: 0.5776 - acc: 0.7857
Epoch 3/10
7/7 [==============================] - 0s 487us/step - loss: 0.5641 - acc: 0.7857
Epoch 4/10
7/7 [==============================] - 0s 271us/step - loss: 0.5527 - acc: 0.7857
Epoch 5/10
7/7 [==============================] - 0s 219us/step - loss: 0.5430 - acc: 0.7857
Epoch 6/10
7/7 [==============================] - 0s 265us/step - loss: 0.5351 - acc: 0.7857
Epoch 7/10
7/7 [==============================] - 0s 227us/step - loss: 0.5290 - acc: 0.7857
Epoch 8/10
7/7 [==============================] - 0s 284us/step - loss: 0.5250 - acc: 0.7857
Epoch 9/10
7/7 [==============================] - 0s 269us/step - loss: 0.5194 - acc: 0.7857
Epoch 10/10
7/7 [==============================] - 0s 299us/step - loss: 0.5145 - acc: 0.7857


In [0]:
model.predict_classes(np.random.random((1, 100)))

array([0])

In [0]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding


model = Sequential()

model.add(Embedding(input_dim=len(data)+1, output_dim=32)) #単語埋め込み層 keras.layers.Embedding
model.add(LSTM(16, return_sequences=False)) #LSTM層 keras.layers.LSTM
model.add(Dense(10, activation='softmax')) #全結合層 keras.layers.Dense

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 32)          256       
_________________________________________________________________
lstm_2 (LSTM)                (None, 16)                3136      
_________________________________________________________________
dense_23 (Dense)             (None, 10)                170       
Total params: 3,562
Trainable params: 3,562
Non-trainable params: 0
_________________________________________________________________


In [0]:
# 各イテレーションのバッチサイズを32で学習を行なう
history = model.fit(data, label, epochs=10, batch_size=32)


Epoch 1/10
7/7 [==============================] - 1s 133ms/step - loss: 0.5769 - acc: 0.7857
Epoch 2/10
7/7 [==============================] - 0s 8ms/step - loss: 0.5764 - acc: 0.7857
Epoch 3/10
7/7 [==============================] - 0s 7ms/step - loss: 0.5759 - acc: 0.7857
Epoch 4/10
7/7 [==============================] - 0s 7ms/step - loss: 0.5753 - acc: 0.7857
Epoch 5/10
7/7 [==============================] - 0s 7ms/step - loss: 0.5748 - acc: 0.7857
Epoch 6/10
7/7 [==============================] - 0s 8ms/step - loss: 0.5742 - acc: 0.7857
Epoch 7/10
7/7 [==============================] - 0s 7ms/step - loss: 0.5737 - acc: 0.7857
Epoch 8/10
7/7 [==============================] - 0s 7ms/step - loss: 0.5731 - acc: 0.7857
Epoch 9/10
7/7 [==============================] - 0s 7ms/step - loss: 0.5725 - acc: 0.7857
Epoch 10/10
7/7 [==============================] - 0s 6ms/step - loss: 0.5719 - acc: 0.7857


In [0]:
import pandas as pd

basket = pd.read_csv("./basketball_comment.csv") 

In [0]:
basket.head()

comment                                             labels
0   Jordan Clarkson is more confident than Michae...                       [player_criticize, team_cav]
1   Somebody told me Dray shoots threes like he's...                                     [player_humor]
2   Did JR just pass up an open three to let the ...                           [player_criticize, play]
3                      Also of course he splashed it  [game_observation, feeling, sentiment_pos, pla...
4   Lebron has been one of Cleveland's best playe...                          [player_praise, team_cav]

In [0]:
basket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1287 entries, 0 to 1286
Data columns (total 2 columns):
comment    1287 non-null object
labels     1287 non-null object
dtypes: object(2)
memory usage: 20.2+ KB


In [0]:
basket.labels

0                            [player_criticize, team_cav]
1                                          [player_humor]
2                                [player_criticize, play]
3       [game_observation, feeling, sentiment_pos, pla...
4                               [player_praise, team_cav]
5                            [player_criticize, team_cav]
6                                        [refs_neg, play]
7                                           [game_praise]
8                      [feeling, player_praise, team_cav]
9                            [player_criticize, team_cav]
10               [player_praise, team_cav, sentiment_pos]
11                                       [game_expertise]
12                              [player_praise, team_cav]
13      [stats, sentiment_neg, player_praise, team_cav...
14               [player_praise, team_cav, sentiment_pos]
15                                        [sentiment_pos]
16                                 [stats, sentiment_pos]
17            

In [0]:
multilabel_binarizer = MultiLabelBinarizer()
multilabel_binarizer.fit(basket.labels)
Y = multilabel_binarizer.transform(basket.labels)

In [0]:
Y.shape

(1287, 31)

In [0]:
Y[0]

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0])

In [0]:
multilabel_binarizer.classes_


array([' ', ',', ':', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g',
       'h', 'i', 'j', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '}'], dtype=object)